### PR TITLE
Add support to custom data

### LINKED ISSUE #426: Add support to custom features(/products)
**Is your feature request related to a problem? Please describe.**
I want to collect and view informations about a software/service/feature that ercole doesn't support/nobody use it in the host page/ercole doesn't want to support it. 

**Describe the solution you'd like**
- Add the possibility to specify the /path/to/custom/fetcherS (with the arguments) that write a JSON type to the stdout in the config.json file.
- The producted JSON type should be marshalled into .Features.Unknown.UnknownFeatures[]
- Ercole web show the Features as tree view (like http://jsonviewer.stack.hu/). I suggest *Unknown features* as name. The tree view should not be shown if  .Features.Unknown.UnknownFeatures == null

**Describe alternatives you've considered**
Create a ercole-agent fork and view the .Features.Unknown.UnknownFeatures with `ercole api get-host`

**Additional context**
This feature is useful for external integrations!

### PR DESCRIPTION
**Pull request by amreo**
Fix #426 
Also fix the swap minimium.

### CODE REVIEW

**Comment by amreo** [comment]
@cirelli94 @raffaelloferrari any thoughts about this PR?

**Comment by raffaelloferrari** [comment]
@amreo can you explain in what way this feature can help Ercole?

**Comment by amreo** [comment]
>  I want to collect and view informations about a software/service/feature that ercole doesn't support/nobody use it in the host page/ercole doesn't want to support it.
Source: https://github.com/ercole-io/ercole/issues/426

**Comment by raffaelloferrari** [comment]
I can't understand are you available for conversation?

**Comment by amreo** [comment]
I am available here. 
Have you seen the image in this PR: https://github.com/ercole-io/ercole-web/pull/222 ?
It's useful for ercole because it permits the user to see some informations about a software/service/feature that ercole doesn't support because the software/service/feature is not common or because ercole doesn't want to support it or because nobody or because it is not already supported by ercole.

For example I want to know if I have registered my host hostname to the DNS server(zone).  The solution I want is that ercole show in the host detail page a something like `{"resolvableHostname": true}`.

**Pull request closed without merging**
