### PR TITLE
Sanitize hostdata

### PR DESCRIPTION
**Pull request by cirelli94**
Add sanitization to hostdata inputs from agents

### CODE REVIEW

**Comment by amreo** [comment]
But what is the purpose of the hostdata JSON????

**Comment by cirelli94** [comment]
> But what is the purpose of the hostdata JSON????

The [hostdata json schema](https://github.com/ercole-io/ercole/blob/master/schema/hostdata.json) purpose is to validate content of the data.
The purpose of the sanitization added in this PR is to check the strings again XSS attempts, something that the JSON schema do not avoid.

e.g. the `idn-hostname` we use for the hostdata name do not avoid to use something like `` that I used in the tests.

**Comment by amreo** [comment]
> The purpose of the sanitization added in this PR is to check the strings again XSS attempts, something that the JSON schema do not avoid.
> 
> e.g. the `idn-hostname` we use for the hostdata name do not avoid to use something like `` that I used in the tests.

But should not XSS protection should be done at frontend level? It seems to me a frontend issue, not a backend issue.
I would expect that frontend developers does not insert string as raw html...

**Comment by cirelli94** [comment]
The API protected here is not one used by the frontend but from the agents.
However, XSS protection must be done on backend level: no one prevent an attacker to call an API directly, without using the agent or the frontend.

**Comment by amreo** [comment]
> However, XSS protection must be done on backend level: no one prevent an attacker to call an API directly, without using the agent or the frontend.

I'm still confused. How can a attacker call a API using XSS [without frontend XSS vulnerabilities]? An attacker can already call the api directly (given she can reach the endpoints).

**Comment by cirelli94** [comment]
XSS protection should be done on both levels, here we are trying to avoid persistent attacks.
Of course the FE should avoid that too :)

**Comment by cirelli94** [comment]
@amreo https://github.com/ercole-io/ercole-web/issues/409
Here with some example for the data from the forms, but of course must be done for the other texts.

**Pull request merged**
